server:
  port: 8082
spring:
  application:
    name: notification-service
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  datasource:
    url: jdbc:mysql://localhost:3308/new_user_db?CreateDatabaseIfNotExist=true
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      schema: resources/db/migration
  flyway:
    enabled: true
  mail:
    from: 476865287@qq.com
    host: smtp.qq.com
    port: 465
    username: 476865287@qq.com
    password: jvyqbkmwvikgcaji
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
          auth: true
    protocol: smtp
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${server.port}

