jpa:
  database-platform: org.hibernate.dialect.MySQL8Dialect
  show-sql: true
  url: jdbc:mysql://localhost:3308/new_user_db?CreateDatabaseIfNotExist=true
  username: root
  password: password
  enable: true
mail:
  from: 476865287@qq.com
  host: smtp.qq.com
  port: 465
  username: 476865287@qq.com
  password: quutapcyhkwsbgef
  enable-ssl: true
  protocol: smtp
