jpa:
  database-platform: org.hibernate.dialect.MySQL8Dialect
  url: jdbc:mysql://product-mysql:3306/product_db?CreateDatabaseIfNotExist=true
  username: root
  password: 123456
  enable: true
  show-sql: true
mail:
  from: 476865287@qq.com
  host: smtp.qq.com
  port: 465
  username: 476865287@qq.com
  password: quutapcyhkwsbgef
  enable-ssl: true
  protocol: smtp
