#server:
#  port: 8080
#spring:
#  application:
#     name: product-service
#  hystrix:
#    command:
#      default:
#        execution:
#          isolation:
#            strategy: SEMAPHORE
#            thread:
#              timeoutInMilliseconds: 10000
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 10485760
#file-save-path: /Users/zemin.yan/Desktop/images/
spring:
  jpa:
    datasource:
      password: 123456
